<?php
/**
 * PaymentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.33.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * PaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getPayments' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPayments
     *
     * Get payments
     *
     * @param  string|null $plugin_payment_token Short-lived token returned from \&quot;getPluginPaymentTokenAsync\&quot; in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \&quot;Calling the Payments REST API from a plugin or widget\&quot; below. (optional)
     * @param  string|null $user_id The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API. (optional)
     * @param  string|null $community_file_id The ID of the Community file to query a user&#39;s payment information on. You can get the Community file ID from the file&#39;s Community page (look for the number after \&quot;file/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $plugin_id The ID of the plugin to query a user&#39;s payment information on. You can get the plugin ID from the plugin&#39;s manifest, or from the plugin&#39;s Community page (look for the number after \&quot;plugin/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $widget_id The ID of the widget to query a user&#39;s payment information on. You can get the widget ID from the widget&#39;s manifest, or from the widget&#39;s Community page (look for the number after \&quot;widget/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\InlineObject25|\OpenAPI\Client\Model\InlineObject40|\OpenAPI\Client\Model\InlineObject46|\OpenAPI\Client\Model\InlineObject48
     */
    public function getPayments($plugin_payment_token = null, $user_id = null, $community_file_id = null, $plugin_id = null, $widget_id = null, string $contentType = self::contentTypes['getPayments'][0])
    {
        list($response) = $this->getPaymentsWithHttpInfo($plugin_payment_token, $user_id, $community_file_id, $plugin_id, $widget_id, $contentType);
        return $response;
    }

    /**
     * Operation getPaymentsWithHttpInfo
     *
     * Get payments
     *
     * @param  string|null $plugin_payment_token Short-lived token returned from \&quot;getPluginPaymentTokenAsync\&quot; in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \&quot;Calling the Payments REST API from a plugin or widget\&quot; below. (optional)
     * @param  string|null $user_id The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API. (optional)
     * @param  string|null $community_file_id The ID of the Community file to query a user&#39;s payment information on. You can get the Community file ID from the file&#39;s Community page (look for the number after \&quot;file/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $plugin_id The ID of the plugin to query a user&#39;s payment information on. You can get the plugin ID from the plugin&#39;s manifest, or from the plugin&#39;s Community page (look for the number after \&quot;plugin/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $widget_id The ID of the widget to query a user&#39;s payment information on. You can get the widget ID from the widget&#39;s manifest, or from the widget&#39;s Community page (look for the number after \&quot;widget/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\InlineObject25|\OpenAPI\Client\Model\InlineObject40|\OpenAPI\Client\Model\InlineObject46|\OpenAPI\Client\Model\InlineObject48, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentsWithHttpInfo($plugin_payment_token = null, $user_id = null, $community_file_id = null, $plugin_id = null, $widget_id = null, string $contentType = self::contentTypes['getPayments'][0])
    {
        $request = $this->getPaymentsRequest($plugin_payment_token, $user_id, $community_file_id, $plugin_id, $widget_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InlineObject25',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InlineObject40',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InlineObject46',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InlineObject48',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\InlineObject25',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InlineObject25',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InlineObject40',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InlineObject46',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InlineObject48',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPaymentsAsync
     *
     * Get payments
     *
     * @param  string|null $plugin_payment_token Short-lived token returned from \&quot;getPluginPaymentTokenAsync\&quot; in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \&quot;Calling the Payments REST API from a plugin or widget\&quot; below. (optional)
     * @param  string|null $user_id The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API. (optional)
     * @param  string|null $community_file_id The ID of the Community file to query a user&#39;s payment information on. You can get the Community file ID from the file&#39;s Community page (look for the number after \&quot;file/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $plugin_id The ID of the plugin to query a user&#39;s payment information on. You can get the plugin ID from the plugin&#39;s manifest, or from the plugin&#39;s Community page (look for the number after \&quot;plugin/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $widget_id The ID of the widget to query a user&#39;s payment information on. You can get the widget ID from the widget&#39;s manifest, or from the widget&#39;s Community page (look for the number after \&quot;widget/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentsAsync($plugin_payment_token = null, $user_id = null, $community_file_id = null, $plugin_id = null, $widget_id = null, string $contentType = self::contentTypes['getPayments'][0])
    {
        return $this->getPaymentsAsyncWithHttpInfo($plugin_payment_token, $user_id, $community_file_id, $plugin_id, $widget_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentsAsyncWithHttpInfo
     *
     * Get payments
     *
     * @param  string|null $plugin_payment_token Short-lived token returned from \&quot;getPluginPaymentTokenAsync\&quot; in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \&quot;Calling the Payments REST API from a plugin or widget\&quot; below. (optional)
     * @param  string|null $user_id The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API. (optional)
     * @param  string|null $community_file_id The ID of the Community file to query a user&#39;s payment information on. You can get the Community file ID from the file&#39;s Community page (look for the number after \&quot;file/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $plugin_id The ID of the plugin to query a user&#39;s payment information on. You can get the plugin ID from the plugin&#39;s manifest, or from the plugin&#39;s Community page (look for the number after \&quot;plugin/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $widget_id The ID of the widget to query a user&#39;s payment information on. You can get the widget ID from the widget&#39;s manifest, or from the widget&#39;s Community page (look for the number after \&quot;widget/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentsAsyncWithHttpInfo($plugin_payment_token = null, $user_id = null, $community_file_id = null, $plugin_id = null, $widget_id = null, string $contentType = self::contentTypes['getPayments'][0])
    {
        $returnType = '\OpenAPI\Client\Model\InlineObject25';
        $request = $this->getPaymentsRequest($plugin_payment_token, $user_id, $community_file_id, $plugin_id, $widget_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPayments'
     *
     * @param  string|null $plugin_payment_token Short-lived token returned from \&quot;getPluginPaymentTokenAsync\&quot; in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \&quot;Calling the Payments REST API from a plugin or widget\&quot; below. (optional)
     * @param  string|null $user_id The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API. (optional)
     * @param  string|null $community_file_id The ID of the Community file to query a user&#39;s payment information on. You can get the Community file ID from the file&#39;s Community page (look for the number after \&quot;file/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $plugin_id The ID of the plugin to query a user&#39;s payment information on. You can get the plugin ID from the plugin&#39;s manifest, or from the plugin&#39;s Community page (look for the number after \&quot;plugin/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string|null $widget_id The ID of the widget to query a user&#39;s payment information on. You can get the widget ID from the widget&#39;s manifest, or from the widget&#39;s Community page (look for the number after \&quot;widget/\&quot; in the URL). Provide exactly one of \&quot;community_file_id\&quot;, \&quot;plugin_id\&quot;, or \&quot;widget_id\&quot;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentsRequest($plugin_payment_token = null, $user_id = null, $community_file_id = null, $plugin_id = null, $widget_id = null, string $contentType = self::contentTypes['getPayments'][0])
    {







        $resourcePath = '/v1/payments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $plugin_payment_token,
            'plugin_payment_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'user_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $community_file_id,
            'community_file_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $plugin_id,
            'plugin_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $widget_id,
            'widget_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Figma-Token');
        if ($apiKey !== null) {
            $headers['X-Figma-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
