<?php
/**
 * ActivityLogEntity
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.33.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ActivityLogEntity Class Doc Comment
 *
 * @category Class
 * @description The resource the actor took the action on. It can be a user, file, project or other resource types.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ActivityLogEntity implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ActivityLog_entity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'id' => 'string',
        'name' => 'string',
        'email' => 'string',
        'key' => 'string',
        'editor_type' => 'string',
        'link_access' => 'string',
        'proto_link_access' => 'string',
        'main_file_key' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'id' => null,
        'name' => null,
        'email' => null,
        'key' => null,
        'editor_type' => null,
        'link_access' => null,
        'proto_link_access' => null,
        'main_file_key' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'id' => false,
        'name' => false,
        'email' => false,
        'key' => false,
        'editor_type' => false,
        'link_access' => false,
        'proto_link_access' => false,
        'main_file_key' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'id' => 'id',
        'name' => 'name',
        'email' => 'email',
        'key' => 'key',
        'editor_type' => 'editor_type',
        'link_access' => 'link_access',
        'proto_link_access' => 'proto_link_access',
        'main_file_key' => 'main_file_key'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'id' => 'setId',
        'name' => 'setName',
        'email' => 'setEmail',
        'key' => 'setKey',
        'editor_type' => 'setEditorType',
        'link_access' => 'setLinkAccess',
        'proto_link_access' => 'setProtoLinkAccess',
        'main_file_key' => 'setMainFileKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'id' => 'getId',
        'name' => 'getName',
        'email' => 'getEmail',
        'key' => 'getKey',
        'editor_type' => 'getEditorType',
        'link_access' => 'getLinkAccess',
        'proto_link_access' => 'getProtoLinkAccess',
        'main_file_key' => 'getMainFileKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_USER = 'user';
    public const TYPE_FILE = 'file';
    public const TYPE_FILE_REPO = 'file_repo';
    public const TYPE_PROJECT = 'project';
    public const TYPE_TEAM = 'team';
    public const TYPE_WORKSPACE = 'workspace';
    public const TYPE_ORG = 'org';
    public const TYPE_PLUGIN = 'plugin';
    public const TYPE_WIDGET = 'widget';
    public const EDITOR_TYPE_FIGMA = 'figma';
    public const EDITOR_TYPE_FIGJAM = 'figjam';
    public const LINK_ACCESS_VIEW = 'view';
    public const LINK_ACCESS_EDIT = 'edit';
    public const LINK_ACCESS_ORG_VIEW = 'org_view';
    public const LINK_ACCESS_ORG_EDIT = 'org_edit';
    public const LINK_ACCESS_INHERIT = 'inherit';
    public const PROTO_LINK_ACCESS_VIEW = 'view';
    public const PROTO_LINK_ACCESS_ORG_VIEW = 'org_view';
    public const PROTO_LINK_ACCESS_INHERIT = 'inherit';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_USER,
            self::TYPE_FILE,
            self::TYPE_FILE_REPO,
            self::TYPE_PROJECT,
            self::TYPE_TEAM,
            self::TYPE_WORKSPACE,
            self::TYPE_ORG,
            self::TYPE_PLUGIN,
            self::TYPE_WIDGET,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEditorTypeAllowableValues()
    {
        return [
            self::EDITOR_TYPE_FIGMA,
            self::EDITOR_TYPE_FIGJAM,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLinkAccessAllowableValues()
    {
        return [
            self::LINK_ACCESS_VIEW,
            self::LINK_ACCESS_EDIT,
            self::LINK_ACCESS_ORG_VIEW,
            self::LINK_ACCESS_ORG_EDIT,
            self::LINK_ACCESS_INHERIT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProtoLinkAccessAllowableValues()
    {
        return [
            self::PROTO_LINK_ACCESS_VIEW,
            self::PROTO_LINK_ACCESS_ORG_VIEW,
            self::PROTO_LINK_ACCESS_INHERIT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('key', $data ?? [], null);
        $this->setIfExists('editor_type', $data ?? [], null);
        $this->setIfExists('link_access', $data ?? [], null);
        $this->setIfExists('proto_link_access', $data ?? [], null);
        $this->setIfExists('main_file_key', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['key'] === null) {
            $invalidProperties[] = "'key' can't be null";
        }
        if ($this->container['editor_type'] === null) {
            $invalidProperties[] = "'editor_type' can't be null";
        }
        $allowedValues = $this->getEditorTypeAllowableValues();
        if (!is_null($this->container['editor_type']) && !in_array($this->container['editor_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'editor_type', must be one of '%s'",
                $this->container['editor_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['link_access'] === null) {
            $invalidProperties[] = "'link_access' can't be null";
        }
        $allowedValues = $this->getLinkAccessAllowableValues();
        if (!is_null($this->container['link_access']) && !in_array($this->container['link_access'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'link_access', must be one of '%s'",
                $this->container['link_access'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['proto_link_access'] === null) {
            $invalidProperties[] = "'proto_link_access' can't be null";
        }
        $allowedValues = $this->getProtoLinkAccessAllowableValues();
        if (!is_null($this->container['proto_link_access']) && !in_array($this->container['proto_link_access'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'proto_link_access', must be one of '%s'",
                $this->container['proto_link_access'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['main_file_key'] === null) {
            $invalidProperties[] = "'main_file_key' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The type of entity.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier of the widget.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the widget.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Email associated with the user's account.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string $key Unique identifier of the file.
     *
     * @return self
     */
    public function setKey($key)
    {
        if (is_null($key)) {
            throw new \InvalidArgumentException('non-nullable key cannot be null');
        }
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets editor_type
     *
     * @return string
     */
    public function getEditorType()
    {
        return $this->container['editor_type'];
    }

    /**
     * Sets editor_type
     *
     * @param string $editor_type Indicates if the object is a widget available on Figma Design or FigJam.
     *
     * @return self
     */
    public function setEditorType($editor_type)
    {
        if (is_null($editor_type)) {
            throw new \InvalidArgumentException('non-nullable editor_type cannot be null');
        }
        $allowedValues = $this->getEditorTypeAllowableValues();
        if (!in_array($editor_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'editor_type', must be one of '%s'",
                    $editor_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['editor_type'] = $editor_type;

        return $this;
    }

    /**
     * Gets link_access
     *
     * @return string
     */
    public function getLinkAccess()
    {
        return $this->container['link_access'];
    }

    /**
     * Sets link_access
     *
     * @param string $link_access Access policy for users who have the link to the file.
     *
     * @return self
     */
    public function setLinkAccess($link_access)
    {
        if (is_null($link_access)) {
            throw new \InvalidArgumentException('non-nullable link_access cannot be null');
        }
        $allowedValues = $this->getLinkAccessAllowableValues();
        if (!in_array($link_access, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'link_access', must be one of '%s'",
                    $link_access,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['link_access'] = $link_access;

        return $this;
    }

    /**
     * Gets proto_link_access
     *
     * @return string
     */
    public function getProtoLinkAccess()
    {
        return $this->container['proto_link_access'];
    }

    /**
     * Sets proto_link_access
     *
     * @param string $proto_link_access Access policy for users who have the link to the file's prototype.
     *
     * @return self
     */
    public function setProtoLinkAccess($proto_link_access)
    {
        if (is_null($proto_link_access)) {
            throw new \InvalidArgumentException('non-nullable proto_link_access cannot be null');
        }
        $allowedValues = $this->getProtoLinkAccessAllowableValues();
        if (!in_array($proto_link_access, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'proto_link_access', must be one of '%s'",
                    $proto_link_access,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['proto_link_access'] = $proto_link_access;

        return $this;
    }

    /**
     * Gets main_file_key
     *
     * @return string
     */
    public function getMainFileKey()
    {
        return $this->container['main_file_key'];
    }

    /**
     * Sets main_file_key
     *
     * @param string $main_file_key Key of the main file.
     *
     * @return self
     */
    public function setMainFileKey($main_file_key)
    {
        if (is_null($main_file_key)) {
            throw new \InvalidArgumentException('non-nullable main_file_key cannot be null');
        }
        $this->container['main_file_key'] = $main_file_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


